-- ============================================================================
-- FIX ORDER SYSTEM: SCHEMA AND RLS UPDATES
-- ============================================================================
-- This script:
-- 1. Adds 'order_code' to the orders table
-- 2. Sets up robust RLS policies for the orders table
-- 3. Configures the storage bucket and its policies
-- ============================================================================

-- 1. SCHEMA UPDATES
-- Add payment columns to orders if they don't exist
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'utr_number') THEN
        ALTER TABLE public.orders ADD COLUMN utr_number TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'payment_screenshot_url') THEN
        ALTER TABLE public.orders ADD COLUMN payment_screenshot_url TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'payment_submitted_at') THEN
        ALTER TABLE public.orders ADD COLUMN payment_submitted_at TIMESTAMP WITH TIME ZONE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'payment_status') THEN
        ALTER TABLE public.orders ADD COLUMN payment_status TEXT DEFAULT 'Pending';
    END IF;
END $$;

-- 2. CREATE PAYMENT_PROOFS TABLE (Alternative/Backup)
CREATE TABLE IF NOT EXISTS public.payment_proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    utr_number TEXT NOT NULL,
    screenshot_url TEXT NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. RLS POLICIES FOR ORDERS TABLE
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Drop existing permissive policies if they exist (clean slate for production)
DROP POLICY IF EXISTS "Allow anon insert orders" ON public.orders;
DROP POLICY IF EXISTS "Allow anon update orders" ON public.orders;
DROP POLICY IF EXISTS "Allow anon read orders" ON public.orders;

-- a. Allow anyone to INSERT a new order
CREATE POLICY "Allow anon insert orders"
ON public.orders
FOR INSERT
TO anon
WITH CHECK (true);

-- b. Allow anyone to SELECT orders
CREATE POLICY "Allow anon read orders"
ON public.orders
FOR SELECT
TO anon
USING (true);

-- c. Allow anyone to UPDATE an order
CREATE POLICY "Allow anon update orders"
ON public.orders
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

-- 4. RLS FOR PAYMENT_PROOFS
ALTER TABLE public.payment_proofs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon insert proofs" ON public.payment_proofs;
DROP POLICY IF EXISTS "Allow anon read proofs" ON public.payment_proofs;

CREATE POLICY "Allow anon insert proofs" ON public.payment_proofs FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon read proofs" ON public.payment_proofs FOR SELECT TO anon USING (true);

-- 5. STORAGE CONFIGURATION
-- Ensure the bucket exists (Supabase keeps this in storage.buckets)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('payment-screenshots', 'payment-screenshots', true)
ON CONFLICT (id) DO NOTHING;

-- RLS for Storage (storage.objects)
-- Drop existing
DROP POLICY IF EXISTS "Allow anon upload payment screenshots" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon read payment screenshots" ON storage.objects;
DROP POLICY IF EXISTS "Allow anon update payment screenshots" ON storage.objects;

-- a. Allow anyone to INSERT (upload) to payment-screenshots bucket
CREATE POLICY "Allow anon upload payment screenshots"
ON storage.objects
FOR INSERT
TO anon
WITH CHECK (
    bucket_id = 'payment-screenshots'
);

-- b. Allow anyone to SELECT (read) from payment-screenshots bucket
CREATE POLICY "Allow anon read payment screenshots"
ON storage.objects
FOR SELECT
TO anon
USING (
    bucket_id = 'payment-screenshots'
);

-- c. Allow anyone to UPDATE (needed for some upload clients)
CREATE POLICY "Allow anon update payment screenshots"
ON storage.objects
FOR UPDATE
TO anon
USING (bucket_id = 'payment-screenshots');

-- ============================================================================
-- VERIFICATION QUERIES (Run these to check state)
-- ============================================================================
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'orders';
-- SELECT * FROM pg_policies WHERE tablename = 'orders';
-- SELECT * FROM storage.buckets WHERE id = 'payment-screenshots';
