-- Seed data for pan_users table
INSERT INTO public.pan_users (pan_number, full_name) VALUES
('BNZPM2501F', 'D MANIKANDAN'),
('BFAPL9762A', 'SELHUVO LOHE'),
('CZBPM5685B', 'SHIV KUMAR MAURYA'),
('CZKPM6229G', 'Manish RUPRAO MOWALE'),
('EJAPS0276M', 'MONIKA MAHADEV SHINDE'),
('BQPPS6188H', 'SUCHISMITA SAHA'),
('BNFPS7312J', 'AJEET KUMAR SHUKLA'),
('BIOPL1856A', '44 ute BABAN LOrAR PRIYANKA'),
('AOSPL9772C', 'KUSUM LATA'),
('BFAPL9762A', 'SELHUVO LOHE'),
('GYOPS8573J', 'SHIVCHARAN')
ON CONFLICT (pan_number) DO NOTHING;
